### PR TITLE
fix(providers): warn if GTIN lookup found multiple results for Spotify / Tidal

### LINKED ISSUE #25: Barcode collision
Sometimes barcodes are not as unique as they should be...

635669065024 returns two different releases (different artists, but same label) with the iTunes, Spotify and Tidal providers. Deezer's API only returns one of them (YBC III), for the others it seems to be random which one is the first result that gets returned.

The iTunes provider at least warns about this, the other providers currently ignore this issue silently.

### PR DESCRIPTION
**Pull request by phw**
For Spotify and Tidal show a warning with a list of URLs if a GTIN lookup found more than one match.

Adapt the existing logic already implemented in iTunes and generalize it by adding a `ReleaseLookup.warnMultipleResults` helper.

Notes:
- Deezer seems to be technically limited to one result
- I don't know about Beatport. Maybe something similar should be done there

This should resolve #25

### CODE REVIEW

**Comment by phw** [comment]
Some thoughts about this in general: In the long term it would be good if there could be some handling of multiple results. Something like this is already mentioned in the roadmap (#6) "Allow providers to return multiple releases, i.e. different variants (e.g. for Bandcamp)".

While testing I had one release that failed the lookup for iTunes due to mismatched track length. However, iTunes found multiple results and one that would have matched the tracklists from other providers was among them. I unfortunately could not find the example again in my notes, but if I do I'll post it.

File: providers/Spotify/mod.ts [hunk 1]
```diff
@@ -173,8 +173,12 @@ export class SpotifyReleaseLookup extends ReleaseApiLookup<SpotifyProvider, Albu
 					this.constructReleaseApiUrl(),
 					this.options.snapshotMaxTimestamp,
 				);
-				if (cacheEntry.content?.albums?.items?.length) {
-					return cacheEntry.content.albums.items[0].id;
+				const releases = cacheEntry.content?.albums?.items;
+				if (releases?.length) {
+					if (releases.length > 1) {
+						this.warnMultipleResults(releases.toSpliced(0, 1).map((release) => release.external_urls?.spotify));
```
Comment (kellnerd) [inline providers/Spotify/mod.ts:179]:
```suggestion
						this.warnMultipleResults(releases.slice(1).map((release) => release.external_urls?.spotify));
```
I had to lookup what `toSpliced` is actually doing, it is a quite new method which does the same as a simple `slice` can do in this case.

File: providers/Tidal/mod.ts [hunk 2]
```diff
@@ -157,6 +157,9 @@ export class TidalReleaseLookup extends ReleaseApiLookup<TidalProvider, Album> {
 				return Boolean(data?.data?.length);
 			};
 			const result = await this.queryAllRegions<Result<Album>>(isValidData);
+			if (result.data.length > 1) {
+				this.warnMultipleResults(result.data.toSpliced(0, 1).map((release) => release.resource.tidalUrl));
```
Comment (kellnerd) [inline providers/Tidal/mod.ts:161]:
```suggestion
				this.warnMultipleResults(result.data.slice(1).map((release) => release.resource.tidalUrl));
```

File: providers/base.ts [hunk 3]
```diff
@@ -335,6 +336,20 @@ export abstract class ReleaseLookup<Provider extends MetadataProvider, RawReleas
 		};
 	}
 
+	/**
+	 * Shows a warning if the provider found more than the expected result for a lookup.
+	 * Expects a list of URLs pointing to the extra results from the provider.
+	 */
+	protected warnMultipleResults(urls: string[] | URL[]) {
+		const lines = urls.map((url) => `${url} ([lookup](/release?url=${encodeURIComponent(String(url))}))`);
```
Comment (kellnerd) [inline providers/base.ts:344]: I like the idea of having a link to initiate a new lookup, it is something which I had also considered doing. My only concern is that the provider implementation now does assumptions on how it is being used, that is how a host-relative link can initiate a lookup on the website.
That is something which I have tried to avoid so far. But I think we can temporarily add this until the providers have a dedicated way to indicate they have multiple results to select from.

Maybe we could use a document-relative link instead which only makes assumptions about the accepted query parameters?
```suggestion
		const lines = urls.map((url) => `${url} ([lookup](?url=${encodeURIComponent(String(url))}))`);
```

**Review by kellnerd — COMMENTED** [review]
Thanks, that was fast!

**Review by kellnerd — APPROVED** [review]

**Comment by kellnerd** [comment]
> While testing I had one release that failed the lookup for iTunes due to mismatched track length. However, iTunes found multiple results and one that would have matched the tracklists from other providers was among them. I unfortunately could not find the example again in my notes, but if I do I'll post it.

I have found the following example in my notes, taken from the server logs:
iTunes returns two totally unrelated releases by different artists: https://harmony.pulsewidth.org.uk/release?gtin=781676664221&itunes=&region=GB&ts=1717878974
Has a different number of tracks also, so it is not your example, but interesting nevertheless.

**Comment by atj** [comment]
> * I don't know about Beatport. Maybe something similar should be done there

Just to clarify, the Beatport provider explicitly returns the first release from the search results with a matching barcode:

https://github.com/kellnerd/harmony/blob/0c9cd5f51a4fbf7cd60e08fdc94ec26f02206537/providers/Beatport/mod.ts#L106

I don't believe I've ever encountered a situation where a GTIN search has returned multiple releases, but the code will either return a single release or `undefined` regardless.
